development:
  adapter: postgresql
  encoding: unicode
  database: hr_development<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD']  %>
  host: <%= ENV['PG_HOST'] || 'localhost' %>
  port: 5432
  
  
test:
  adapter: postgresql
  encoding: unicode
  database: hr_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: <%= ENV['PG_HOST'] || 'localhost' %>
  port: 5432


production:
  adapter: postgresql
  encoding: unicode
  database: hr_production
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: 5432
